/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	cgroupnotifycrdv1 "github.com/tencent/caelus/pkg/apis/cgroupnotifycrd/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCgroupNotifyCrds implements CgroupNotifyCrdInterface
type FakeCgroupNotifyCrds struct {
	Fake *FakeCgroupnotifycrdV1
	ns   string
}

var cgroupnotifycrdsResource = schema.GroupVersionResource{Group: "cgroupnotifycrd", Version: "v1", Resource: "cgroupnotifycrds"}

var cgroupnotifycrdsKind = schema.GroupVersionKind{Group: "cgroupnotifycrd", Version: "v1", Kind: "CgroupNotifyCrd"}

// Get takes name of the cgroupNotifyCrd, and returns the corresponding cgroupNotifyCrd object, and an error if there is any.
func (c *FakeCgroupNotifyCrds) Get(ctx context.Context, name string, options v1.GetOptions) (result *cgroupnotifycrdv1.CgroupNotifyCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cgroupnotifycrdsResource, c.ns, name), &cgroupnotifycrdv1.CgroupNotifyCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cgroupnotifycrdv1.CgroupNotifyCrd), err
}

// List takes label and field selectors, and returns the list of CgroupNotifyCrds that match those selectors.
func (c *FakeCgroupNotifyCrds) List(ctx context.Context, opts v1.ListOptions) (result *cgroupnotifycrdv1.CgroupNotifyCrdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cgroupnotifycrdsResource, cgroupnotifycrdsKind, c.ns, opts), &cgroupnotifycrdv1.CgroupNotifyCrdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cgroupnotifycrdv1.CgroupNotifyCrdList{ListMeta: obj.(*cgroupnotifycrdv1.CgroupNotifyCrdList).ListMeta}
	for _, item := range obj.(*cgroupnotifycrdv1.CgroupNotifyCrdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cgroupNotifyCrds.
func (c *FakeCgroupNotifyCrds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cgroupnotifycrdsResource, c.ns, opts))

}

// Create takes the representation of a cgroupNotifyCrd and creates it.  Returns the server's representation of the cgroupNotifyCrd, and an error, if there is any.
func (c *FakeCgroupNotifyCrds) Create(ctx context.Context, cgroupNotifyCrd *cgroupnotifycrdv1.CgroupNotifyCrd, opts v1.CreateOptions) (result *cgroupnotifycrdv1.CgroupNotifyCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cgroupnotifycrdsResource, c.ns, cgroupNotifyCrd), &cgroupnotifycrdv1.CgroupNotifyCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cgroupnotifycrdv1.CgroupNotifyCrd), err
}

// Update takes the representation of a cgroupNotifyCrd and updates it. Returns the server's representation of the cgroupNotifyCrd, and an error, if there is any.
func (c *FakeCgroupNotifyCrds) Update(ctx context.Context, cgroupNotifyCrd *cgroupnotifycrdv1.CgroupNotifyCrd, opts v1.UpdateOptions) (result *cgroupnotifycrdv1.CgroupNotifyCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cgroupnotifycrdsResource, c.ns, cgroupNotifyCrd), &cgroupnotifycrdv1.CgroupNotifyCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cgroupnotifycrdv1.CgroupNotifyCrd), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCgroupNotifyCrds) UpdateStatus(ctx context.Context, cgroupNotifyCrd *cgroupnotifycrdv1.CgroupNotifyCrd, opts v1.UpdateOptions) (*cgroupnotifycrdv1.CgroupNotifyCrd, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cgroupnotifycrdsResource, "status", c.ns, cgroupNotifyCrd), &cgroupnotifycrdv1.CgroupNotifyCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cgroupnotifycrdv1.CgroupNotifyCrd), err
}

// Delete takes name of the cgroupNotifyCrd and deletes it. Returns an error if one occurs.
func (c *FakeCgroupNotifyCrds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(cgroupnotifycrdsResource, c.ns, name, opts), &cgroupnotifycrdv1.CgroupNotifyCrd{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCgroupNotifyCrds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cgroupnotifycrdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &cgroupnotifycrdv1.CgroupNotifyCrdList{})
	return err
}

// Patch applies the patch and returns the patched cgroupNotifyCrd.
func (c *FakeCgroupNotifyCrds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cgroupnotifycrdv1.CgroupNotifyCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cgroupnotifycrdsResource, c.ns, name, pt, data, subresources...), &cgroupnotifycrdv1.CgroupNotifyCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cgroupnotifycrdv1.CgroupNotifyCrd), err
}
