/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/tencent/caelus/pkg/apis/cgroupnotifycrd/v1"
	scheme "github.com/tencent/caelus/pkg/cgroupClient/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CgroupNotifyCrdsGetter has a method to return a CgroupNotifyCrdInterface.
// A group's client should implement this interface.
type CgroupNotifyCrdsGetter interface {
	CgroupNotifyCrds(namespace string) CgroupNotifyCrdInterface
}

// CgroupNotifyCrdInterface has methods to work with CgroupNotifyCrd resources.
type CgroupNotifyCrdInterface interface {
	Create(ctx context.Context, cgroupNotifyCrd *v1.CgroupNotifyCrd, opts metav1.CreateOptions) (*v1.CgroupNotifyCrd, error)
	Update(ctx context.Context, cgroupNotifyCrd *v1.CgroupNotifyCrd, opts metav1.UpdateOptions) (*v1.CgroupNotifyCrd, error)
	UpdateStatus(ctx context.Context, cgroupNotifyCrd *v1.CgroupNotifyCrd, opts metav1.UpdateOptions) (*v1.CgroupNotifyCrd, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CgroupNotifyCrd, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CgroupNotifyCrdList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CgroupNotifyCrd, err error)
	CgroupNotifyCrdExpansion
}

// cgroupNotifyCrds implements CgroupNotifyCrdInterface
type cgroupNotifyCrds struct {
	client rest.Interface
	ns     string
}

// newCgroupNotifyCrds returns a CgroupNotifyCrds
func newCgroupNotifyCrds(c *CgroupnotifycrdV1Client, namespace string) *cgroupNotifyCrds {
	return &cgroupNotifyCrds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cgroupNotifyCrd, and returns the corresponding cgroupNotifyCrd object, and an error if there is any.
func (c *cgroupNotifyCrds) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CgroupNotifyCrd, err error) {
	result = &v1.CgroupNotifyCrd{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CgroupNotifyCrds that match those selectors.
func (c *cgroupNotifyCrds) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CgroupNotifyCrdList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CgroupNotifyCrdList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cgroupNotifyCrds.
func (c *cgroupNotifyCrds) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cgroupNotifyCrd and creates it.  Returns the server's representation of the cgroupNotifyCrd, and an error, if there is any.
func (c *cgroupNotifyCrds) Create(ctx context.Context, cgroupNotifyCrd *v1.CgroupNotifyCrd, opts metav1.CreateOptions) (result *v1.CgroupNotifyCrd, err error) {
	result = &v1.CgroupNotifyCrd{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cgroupNotifyCrd).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cgroupNotifyCrd and updates it. Returns the server's representation of the cgroupNotifyCrd, and an error, if there is any.
func (c *cgroupNotifyCrds) Update(ctx context.Context, cgroupNotifyCrd *v1.CgroupNotifyCrd, opts metav1.UpdateOptions) (result *v1.CgroupNotifyCrd, err error) {
	result = &v1.CgroupNotifyCrd{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		Name(cgroupNotifyCrd.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cgroupNotifyCrd).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *cgroupNotifyCrds) UpdateStatus(ctx context.Context, cgroupNotifyCrd *v1.CgroupNotifyCrd, opts metav1.UpdateOptions) (result *v1.CgroupNotifyCrd, err error) {
	result = &v1.CgroupNotifyCrd{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		Name(cgroupNotifyCrd.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cgroupNotifyCrd).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cgroupNotifyCrd and deletes it. Returns an error if one occurs.
func (c *cgroupNotifyCrds) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cgroupNotifyCrds) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cgroupNotifyCrd.
func (c *cgroupNotifyCrds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CgroupNotifyCrd, err error) {
	result = &v1.CgroupNotifyCrd{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cgroupnotifycrds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
