//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CgroupNotifyCrd) DeepCopyInto(out *CgroupNotifyCrd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CgroupNotifyCrd.
func (in *CgroupNotifyCrd) DeepCopy() *CgroupNotifyCrd {
	if in == nil {
		return nil
	}
	out := new(CgroupNotifyCrd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CgroupNotifyCrd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CgroupNotifyCrdList) DeepCopyInto(out *CgroupNotifyCrdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CgroupNotifyCrd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CgroupNotifyCrdList.
func (in *CgroupNotifyCrdList) DeepCopy() *CgroupNotifyCrdList {
	if in == nil {
		return nil
	}
	out := new(CgroupNotifyCrdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CgroupNotifyCrdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CgroupNotifyCrdSpec) DeepCopyInto(out *CgroupNotifyCrdSpec) {
	*out = *in
	in.MemoryCgroup.DeepCopyInto(&out.MemoryCgroup)
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CgroupNotifyCrdSpec.
func (in *CgroupNotifyCrdSpec) DeepCopy() *CgroupNotifyCrdSpec {
	if in == nil {
		return nil
	}
	out := new(CgroupNotifyCrdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CgroupNotifyCrdStatus) DeepCopyInto(out *CgroupNotifyCrdStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CgroupNotifyCrdStatus.
func (in *CgroupNotifyCrdStatus) DeepCopy() *CgroupNotifyCrdStatus {
	if in == nil {
		return nil
	}
	out := new(CgroupNotifyCrdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryNotifyConfig) DeepCopyInto(out *MemoryNotifyConfig) {
	*out = *in
	if in.Pressures != nil {
		in, out := &in.Pressures, &out.Pressures
		*out = make([]MemoryPressureNotifyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]MemoryUsageNotifyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryNotifyConfig.
func (in *MemoryNotifyConfig) DeepCopy() *MemoryNotifyConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryNotifyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryPressureNotifyConfig) DeepCopyInto(out *MemoryPressureNotifyConfig) {
	*out = *in
	if in.Cgroups != nil {
		in, out := &in.Cgroups, &out.Cgroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryPressureNotifyConfig.
func (in *MemoryPressureNotifyConfig) DeepCopy() *MemoryPressureNotifyConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryPressureNotifyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryUsageNotifyConfig) DeepCopyInto(out *MemoryUsageNotifyConfig) {
	*out = *in
	if in.Cgroups != nil {
		in, out := &in.Cgroups, &out.Cgroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryUsageNotifyConfig.
func (in *MemoryUsageNotifyConfig) DeepCopy() *MemoryUsageNotifyConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryUsageNotifyConfig)
	in.DeepCopyInto(out)
	return out
}
