/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	cgroupnotifycrdv1 "github.com/tencent/caelus/pkg/apis/cgroupnotifycrd/v1"
	versioned "github.com/tencent/caelus/pkg/cgroupClient/clientset/versioned"
	internalinterfaces "github.com/tencent/caelus/pkg/cgroupClient/informers/externalversions/internalinterfaces"
	v1 "github.com/tencent/caelus/pkg/cgroupClient/listers/cgroupnotifycrd/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CgroupNotifyCrdInformer provides access to a shared informer and lister for
// CgroupNotifyCrds.
type CgroupNotifyCrdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CgroupNotifyCrdLister
}

type cgroupNotifyCrdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCgroupNotifyCrdInformer constructs a new informer for CgroupNotifyCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCgroupNotifyCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCgroupNotifyCrdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCgroupNotifyCrdInformer constructs a new informer for CgroupNotifyCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCgroupNotifyCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CgroupnotifycrdV1().CgroupNotifyCrds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CgroupnotifycrdV1().CgroupNotifyCrds(namespace).Watch(context.TODO(), options)
			},
		},
		&cgroupnotifycrdv1.CgroupNotifyCrd{},
		resyncPeriod,
		indexers,
	)
}

func (f *cgroupNotifyCrdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCgroupNotifyCrdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cgroupNotifyCrdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cgroupnotifycrdv1.CgroupNotifyCrd{}, f.defaultInformer)
}

func (f *cgroupNotifyCrdInformer) Lister() v1.CgroupNotifyCrdLister {
	return v1.NewCgroupNotifyCrdLister(f.Informer().GetIndexer())
}
